affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 7
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 2
sb_trainable: true
sp_trainable: true
state_id: 4
symbolic.funs_name.0:
- - x
  - x
  - '0'
symbolic.funs_name.1:
- - x
symbolic_enabled: true
width:
- - 3
  - 0
- - 1
  - 0
- - 1
  - 0
